server:
  port: 8000
valkey:
  host: 127.0.0.1
  port: 6379
  db: 8
cpe:
  path: './data/nvdcpe-2.0.tar'
  source: 'https://nvd.nist.gov/feeds/json/cpe/2.0/nvdcpe-2.0.tar.gz'
cvelistv5:
  path: './data/cvelistv5.ndjson'
  source: 'https://vulnerability.circl.lu/dumps/cvelistv5.ndjson'
